name: Multi-platform CMake build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  mingw:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Mingw
      run: choco install mingw -y

    - name: Run CMake
      run: cmake -G "MinGW Makefiles" -S . -B build

    - name: Build using CMake
      run: cmake --build build --config Release

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: EPOLIS-windows
        path: build/bin

  gcc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install GCC
      run: sudo apt-get install gcc -y

    - name: Install GTK3
      run: sudo apt-get install libgtk-3-dev -y

    - name: Run CMake
      run: cmake -S . -B build

    - name: Build using CMake
      run: cmake --build build --config Release

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: EPOLIS-linux
        path: build/bin