name: Build project for Windows
on:
  workflow_dispatch:

jobs:
  mingw:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Mingw
        run: choco install mingw -y

      - name: Run CMake
        run: cmake -G "MinGW Makefiles" -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build using CMake
        run: cmake --build build

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: EPOLIS-windows
          path: build/bin